# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildApi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./RiverLoggerApi/
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run restore build and test script
      run: sh ../scripts/DotnetBuild.sh
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./RiverLoggerApi/
        args: >
          -Dsonar.sources=lib/
          -Dsonar.test.exclusions=tests/**
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  buildMaui:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./RiverLoggerMobileApp/
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run restore build and test script
      run: sh ../scripts/DotnetBuild.sh
